### ISSUE TITLE
How to generate static documentation file?

### ISSUE THREAD

**Issue by qortex** [mrin9/OpenAPI-Viewer#1]
How is it possible to generate a static documentation from an Open API file (all included HTML & supporting files) ?

Thanks for the awesome work!

**Comment by mrin9** [comment]
Unfortunately, thats not the goal of this project and not possible with the current architecture choices. Providing that option would mean it either needs to be a command line tool, or should depend on server-side  processing for the generation of files.

**Comment by qortex** [comment]
Makes sense, thanks!
