### ISSUE TITLE
Way to disable "try" feature?

### ISSUE THREAD

**Issue by qortex** [mrin9/OpenAPI-Viewer#2]
Is it possible to disable all the fields for dynamic testing and make it look like a static doc?

**Comment by mrin9** [comment]
to disable 'Try', you can click on the gear icon on top-right , and disable 'Developer Mode'. This will make 'Try' button disappear . The input fields wont be disabled coz, sometimes these inputs can contain examples provided in the spec. If the examples are too long to fit in the input, it allows you to scroll to the end. Disabling it would mean you will end up showing partial content.

Now that being said its a manual process, if you want to present this to a customer as a static document by default, you wont be able to do that.

However keep an eye on this space, I am working on a ```custom-element``` that will be independent of any framework and would allow you to use it in any browser, it will provide you more options including to make it a real static doc.

If everything goes per plan I will be releasing the first beta in a month

**Comment by qortex** [comment]
Awesome, thanks!
