### ISSUE TITLE
Getting started documentation

### ISSUE THREAD

**Issue by AarjavP** [mrin9/OpenAPI-Viewer#3]
Looking for more documentation that is similar to swagger-ui's seen here: https://github.com/swagger-api/swagger-ui#usage

Mainly these 2 topics: 
- [ ] installation into another project/page, e.g. can I do something like `SwaggerUI({dom_id: '#myDomId'})` ? 
- [ ] configuration options, doesn't have to include everything but things like if there's a place I can set url used to retrieve the open api spec

**Comment by mrin9** [comment]
for now it is pretty rigid, All you can do is copy the `dist` folder onto your WebServers `public` path and then 
- modify `index.html` to your desired structure
- or insert an `iframe` in your page(html) and point the `<iframe src=>` to index.html

But keep an eye on this space. I am working on `<custom-element>` which will be free of any frameworks to allow you to seamlessly integrate into any other page additionally  will have a bunch of options for personalization such as 
- Replace logo
- Brand colors
- Brand Font


I am trying to wrap-up the initial beta in a months time, so documentation is talking a back seat.
Will keep this issue open as documentation is in the plans

**Comment by AarjavP** [comment]
Alright, makes sense. This does look very promising!

**Comment by mrin9** [comment]
There isn't much scope if you are trying to use this to integrate this any other Html-Doc. But checkout [RapiDoc](https://mrin9.github.io/RapiDoc/). It has some documentation and also allows you to integrate with other HTMLs.
Hope that answers your concerns
