### ISSUE TITLE
Error parsing the spec, that passes the validation of openapi-spec-validator

### ISSUE THREAD

**Issue by jduquennoy** [mrin9/OpenAPI-Viewer#4]
Hi,

First, thanks a lot for this awesome work. It really is great.

After expanding my doc, I ended up receiving a "Oops, Error encountered while parsing the Spec" when I load it into openAPI Viewer.
When passing it through openapi-spec-validator, it sees it as valid.

I found no easy way to know what node of the json structure causes the problem. I will continue searching by removing parts of my doc progressively, but meanwhile, please find attached the doc that causes this parsing error.

[openAPI.json.zip](https://github.com/mrin9/OpenAPI-Viewer/files/2825560/openAPI.json.zip)

thanks again for this great work !

**Comment by mrin9** [comment]
Hi,
Currently I am concentrating on a different project which is too is a swagger viewer and pretty similar to this one. I tried the OpenAPI spec you attached in that project and it worked fine there. 

checkout [RapiDoc](https://mrin9.github.io/RapiDoc/) if it takes care of your use case

**Comment by mrin9** [comment]
closing this issue, this may be an issue in the spec
