### ISSUE TITLE
Body required params & Model

### ISSUE THREAD

**Issue by Khyme** [mrin9/OpenAPI-Viewer#5]
Hello,

Nice project. I have a few questions / remarks though.

I don't think there's a symbol to show required properties when in Model tab, using body parameters ? Like there could be [here](https://petstore.swagger.io/#/pet/updatePet) for example with the red stars.

Also description for arrays is never displayed. Example of OAS3 representing the case :
 `          "list" : {
            "type" : "array",
            "description" : "My description",
            "items" : {
              "type" : "object",
              "description" : "My description"
            }
          }`

As is min and max items for Arrays

`          "list" : {
            "maxItems" : 1000,
            "minItems" : 0,
            "type" : "array",
            "description" : "My description",
            "items" : {
              "$ref" : "#/components/schemas/Item"
            }
          }`

Also do you plan on implementing a global model tab with all schemas ?

Thanks again.

**Comment by mrin9** [comment]
would you consider to move to **RapiDoc** https://mrin9.github.io/RapiDoc/ ?

Currently, I am focusing on [RapiDoc]( https://github.com/mrin9/RapiDoc 
) project, so updates to this project will be little delayed. But I plan to keep both of them in sync

If you are unable to move to RapiDoc, let me know whats the concern is, and I will see if i can resolve it.

Having said that, the issue that you mentioned was an [issue]( https://github.com/mrin9/RapiDoc/issues/23) in RapiDoc too, which is now fixed
Regarding your other question, to have a global schema section. I do not plan to create one for now
 
My main reason not to have a global schema is,  in my experience, people do not use that section so much and most importantly for a larger specs that is spanned across multiple files, it becomes a performance bottleneck

But if you can provide me a compelling reason I might consider adding it

**Comment by Khyme** [comment]
Hello

No , sadly I'd like to use vue.

As for the required properties I developed it. Example below (also working for nested objects of course) :
![Screenshot_20190506_155245](https://user-images.githubusercontent.com/36672148/57229791-3c50d580-7017-11e9-9930-c1102aae1ec2.png)

With json 

`  "components" : {
    "schemas" : {
      "MyObject" : {
        "required" : [ "name", "status" ],
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string",
            "example" : "Come say hi !"
          },
          "status" : {
            "type" : "string",
            "enum" : [ "active", "inactive", "draft", "archive" ]
          },
          "start" : {
            "type" : "string",
            "format" : "date-time"
          },
          "end" : {
            "type" : "string",
            "format" : "date-time"
          }
}
}
}`
Will do the same with descriptions soonish. If it's of interest I can share. Not styled yet as it'll probably get revamped in my project.

Global schema I'll do in some custom descriptions in the page after all so no problem. Not a big fan of it myself, but it's not my decision to make.

Thanks again.

**Comment by mrin9** [comment]
I am happy to accept a PR for the required properties. Once you style them and run through some really large schemas

Thanks
