### ISSUE TITLE
Post with json body

### ISSUE THREAD

**Issue by albertodeago** [mrin9/OpenAPI-Viewer#6]
Hello, thanks for the amazing project.

Probably I'm missing something really stupid.
If I use a json like "https://petstore.swagger.io/v2/swagger.json"
and I try to use the API "/store/order" that has a json body, the request is always missing the body...

Am I missing something?

**Comment by mrin9** [comment]
it is stemming from some kind of restriction/rules put on the requests originating across domains  (CORS). It doesn't give enough information in responses or in its header as what could have been going wrong. 
I am sorry I wont be able to help in this matter. 
Also I would urge you to switch to RapiDoc (https://mrin9.github.io/RapiDoc) if you can as this project would be getting little delayed responses, we have plans to update this project once Vue-3 is out

**Comment by albertodeago** [comment]
Mmh, i don't see any cors issue, I just see on the network the request without the body. 
I'll try to debug it and in case make a PR
